repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.18
  hooks:
    - id: shellcheck
    - id: shfmt
- repo: https://github.com/markdownlint/markdownlint
  rev: v0.13.0
  hooks:
    - id: markdownlint
      entry: mdl
      files: \.(md|mdown|markdown)$
- repo: https://github.com/thlorenz/doctoc
  rev: v2.2.0
  hooks:
    - id: doctoc
